export const users = [
  {
    id: 1,
    username: "john_doe",
    email: "john.doe@example.com",
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    role: "admin",
    created_at: "2025-01-15T08:00:00Z",
    _destroy: false,
    passwordHash: "hashed_password_1",
    isActive: true,
  },
  {
    id: 2,
    username: "jane_smith",
    email: "jane.smith@example.com",
    avatar: "https://randomuser.me/api/portraits/women/1.jpg",
    role: "user",
    created_at: "2025-01-16T08:00:00Z",
    _destroy: false,
    passwordHash: "hashed_password_2",
    isActive: true,
  },
  {
    id: 3,
    username: "michael_jones",
    email: "michael.jones@example.com",
    avatar: "https://randomuser.me/api/portraits/men/2.jpg",
    role: "user",
    created_at: "2025-02-01T08:00:00Z",
    _destroy: false,
    passwordHash: "hashed_password_3",
    isActive: true,
  },
  {
    id: 4,
    username: "lisa_taylor",
    email: "lisa.taylor@example.com",
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    role: "user",
    created_at: "2025-02-10T08:00:00Z",
    _destroy: false,
    passwordHash: "hashed_password_4",
    isActive: true,
  },
  {
    id: 5,
    username: "alex_lee",
    email: "alex.lee@example.com",
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    role: "user",
    created_at: "2025-02-12T08:00:00Z",
    _destroy: false,
    passwordHash: "hashed_password_5",
    isActive: true,
  },
];

export const events = [
  // Appointment Type
  {
    id: 1,
    title: "Team Meeting",
    description: "Discussing quarterly goals.",
    user_id: 1,
    status: "active",
    start_time: "2025-02-09T10:00:00Z",
    end_time: "2025-02-09T11:00:00Z",
    _destroy: false,
    type: "appointment",
    url: "http://example.com",
    color: "#FFE4C8", // Light Orange
    create_at: "2025-02-06T08:00:00Z",
  },
  {
    id: 2,
    title: "Client Call",
    description: "Client check-in for progress review.",
    user_id: 2,
    status: "active",
    start_time: "2025-02-06T14:00:00Z",
    end_time: "2025-02-06T15:00:00Z",
    _destroy: false,
    type: "appointment",
    url: "http://example.com",
    color: "#F9BE81", // Dark Orange
    create_at: "2025-02-03T09:00:00Z",
  },
  {
    id: 3,
    title: "Webinar: Project Management Tools",
    description: "Exploring popular project management tools.",
    user_id: 3,
    status: "active",
    start_time: "2025-02-10T15:00:00Z",
    end_time: "2025-02-10T16:00:00Z",
    _destroy: false,
    type: "appointment",
    url: "http://example.com",
    color: "#5684AE", // Light Blue
    create_at: "2025-02-05T08:00:00Z",
  },

  // Event Type
  {
    id: 4,
    title: "Team Building Activity",
    description: "Outdoor team-building activities.",
    user_id: 4,
    status: "active",
    start_time: "2025-02-14T08:00:00Z",
    end_time: "2025-02-14T17:00:00Z",
    _destroy: false,
    type: "event",
    url: "http://example.com",
    color: "#0F4C81", // Dark Blue
    create_at: "2025-02-10T08:00:00Z",
  },
  {
    id: 5,
    title: "Annual Company Conference",
    description: "Annual conference with all departments.",
    user_id: 5,
    status: "active",
    start_time: "2025-03-01T09:00:00Z",
    end_time: "2025-03-01T17:00:00Z",
    _destroy: false,
    type: "event",
    url: "http://example.com",
    color: "#5684AE", // Light Blue
    create_at: "2025-02-20T08:00:00Z",
  },

  // Additional events
  {
    id: 6,
    title: "Product Launch Event",
    description: "Launching new products in the market.",
    user_id: 3,
    status: "active",
    start_time: "2025-02-18T10:00:00Z",
    end_time: "2025-02-18T12:00:00Z",
    _destroy: false,
    type: "event",
    url: "http://example.com",
    color: "#FFE4C8", // Light Orange
    create_at: "2025-02-15T09:00:00Z",
  },
  {
    id: 7,
    title: "Customer Feedback Session",
    description: "Gathering customer feedback on products.",
    user_id: 2,
    status: "active",
    start_time: "2025-02-20T14:00:00Z",
    end_time: "2025-02-20T15:00:00Z",
    _destroy: false,
    type: "appointment",
    url: "http://example.com",
    color: "#F9BE81", // Dark Orange
    create_at: "2025-02-15T10:00:00Z",
  },
  {
    id: 8,
    title: "Hackathon Kickoff",
    description: "Start of the internal company hackathon.",
    user_id: 1,
    status: "active",
    start_time: "2025-02-25T09:00:00Z",
    end_time: "2025-02-25T12:00:00Z",
    _destroy: false,
    type: "event",
    url: "http://example.com",
    color: "#0F4C81", // Dark Blue
    create_at: "2025-02-18T09:00:00Z",
  },
  {
    id: 9,
    title: "Staff Meeting",
    description: "Meeting with the internal staff for updates.",
    user_id: 4,
    status: "active",
    start_time: "2025-02-28T13:00:00Z",
    end_time: "2025-02-28T14:00:00Z",
    _destroy: false,
    type: "appointment",
    url: "http://example.com",
    color: "#F9BE81", // Dark Orange
    create_at: "2025-02-20T11:00:00Z",
  },
  {
    id: 10,
    title: "Marketing Strategy Workshop",
    description: "Planning marketing strategy for the next quarter.",
    user_id: 5,
    status: "active",
    start_time: "2025-03-05T14:00:00Z",
    end_time: "2025-03-05T17:00:00Z",
    _destroy: false,
    type: "event",
    url: "http://example.com",
    color: "#F9BE81",
    create_at: "2025-02-25T13:00:00Z",
  },
  {
    id: 11,
    title: "Team Weekly Sync",
    description: "Weekly team sync-up for ongoing projects.",
    user_id: 1,
    status: "active",
    start_time: "2025-02-15T16:00:00Z",
    end_time: "2025-02-15T17:00:00Z",
    _destroy: false,
    type: "appointment",
    url: "http://example.com",
    color: "#5684AE", // Light Blue
    create_at: "2025-02-10T09:00:00Z",
  },
];

export const recurrences = [
  { id: 1, event_id: 1, frequency: "weekly", interval: 1 },
  { id: 2, event_id: 2, frequency: "monthly", interval: 1 },
  { id: 3, event_id: 3, frequency: "weekly", interval: 1 },
  { id: 4, event_id: 4, frequency: "none", interval: 0 },
];
